# Generated by Django 5.2.5 on 2025-08-17 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='reporters/profile_pics/', verbose_name='Фото профиля')),
                ('hire_date', models.DateField(auto_now_add=True, verbose_name='Дата найма')),
                ('specialization', models.CharField(blank=True, max_length=100, verbose_name='Специализация')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Репортер',
                'verbose_name_plural': 'Репортеры',
                'ordering': ['-hire_date'],
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст новости')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/images/', verbose_name='Изображение')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_posts', to='news.reporter', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Новостной пост',
                'verbose_name_plural': 'Новостные посты',
                'ordering': ['-created_at'],
            },
        ),
    ]
