# Generated by Django 5.2.5 on 2025-08-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_reporter_newspost'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('team_photo', models.ImageField(blank=True, upload_to='about/', verbose_name='Фото команды')),
                ('stats', models.JSONField(blank=True, default=dict, verbose_name='Статистика')),
            ],
            options={
                'verbose_name': "Страница 'О нас'",
                'verbose_name_plural': "Страницы 'О нас'",
            },
        ),
    ]
