# Generated by Django 5.2.5 on 2025-08-18 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_aboutpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsPost',
            new_name='NewsItem',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.newsitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
