# Generated by Django 5.2.5 on 2025-08-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_comment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='voice_messages/'),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_voice_message',
            field=models.BooleanField(default=False),
        ),
    ]
