# Generated by Django 5.2.5 on 2025-08-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_comment_options_comment_audio_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
