# Generated by Django 5.2.5 on 2025-08-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_reporter_user_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custom_status',
            field=models.CharField(blank=True, max_length=100, verbose_name='Пользовательский статус'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_reporter',
            field=models.BooleanField(default=False, verbose_name='Репортёр'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, verbose_name='Последняя активность'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('online', 'В сети'), ('idle', 'Неактивен'), ('dnd', 'Не беспокоить'), ('offline', 'Не в сети'), ('invisible', 'Невидимый')], default='online', max_length=20, verbose_name='Статус'),
        ),
    ]
