# Generated by Django 5.2.5 on 2025-08-24 16:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_userprofile_custom_status_userprofile_is_reporter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='custom_status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_reporter',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последняя активность'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('online', 'В сети'), ('idle', 'Неактивен'), ('dnd', 'Не беспокоить'), ('offline', 'Не в сети'), ('invisible', 'Невидимый')], default='offline', max_length=20, verbose_name='Статус'),
        ),
    ]
